package com.zr.nebulademo

object DummyMessageGenerator {

    val infoMessages = listOf(
        "Request API create store started",
        "Request API update product executed",
        "User session initialized successfully",
        "Cache loaded from local storage",
        "Database connection established",
        "Token refreshed successfully",
        "Sync process completed",
        "Remote config fetched",
        "Application entered foreground",
        "User authentication succeeded",
        "Request API fetch order list started",
        "Image resource loaded from disk",
        "Preferences updated successfully",
        "Background worker scheduled",
        "Notification dispatched",
        "Pagination request triggered",
        "User profile loaded",
        "Feature flag enabled",
        "Data binding completed",
        "Analytics event sent",
        "Request API delete cart item started",
        "Local cache hit",
        "Session restored from persistence",
        "File upload started",
        "Socket connection opened"
    )

    val debugMessages = listOf(
        "Request payload serialized to JSON",
        "Response body size is 12KB",
        "Mapping DTO to domain model",
        "Thread switched to IO dispatcher",
        "SQL query executed in 14ms",
        "Retry count incremented to 2",
        "Pagination offset calculated",
        "Headers added to request",
        "Parsing date string to LocalDate",
        "Coroutine launched in ViewModel scope",
        "DiffUtil calculation completed",
        "Cache key generated",
        "Response code received: 200",
        "Using fallback value for null field",
        "Executing transaction block",
        "Flow emission collected",
        "Mutex lock acquired",
        "Network timeout set to 30s",
        "Serialized object written to disk",
        "Using mock data source",
        "Interceptor invoked",
        "Lazy initialization executed",
        "Adapter list updated",
        "State reduced to Success",
        "Debug flag enabled"
    )

    val warningMessages = listOf(
        "Response time is slower than expected",
        "Cache miss detected",
        "Using deprecated API endpoint",
        "Token will expire soon",
        "Fallback to local data source",
        "Retrying request after timeout",
        "Image resource not found, using placeholder",
        "Partial data received from server",
        "Skipping invalid item in list",
        "Pagination returned empty page",
        "Configuration value missing, using default",
        "Database version mismatch detected",
        "Network connection is unstable",
        "Ignoring duplicate request",
        "Rate limit almost exceeded",
        "Field value truncated",
        "Invalid input detected but ignored",
        "Using legacy implementation",
        "Background task delayed",
        "Response schema changed",
        "Inconsistent cache state detected",
        "Slow disk write detected",
        "Memory usage is high",
        "UI rendering took longer than expected",
        "Unrecognized enum value received"
    )

    val errorMessages = listOf(
        "Request API create store failed",
        "Response failed to be parsed",
        "NullPointerException in Repository layer",
        "Database migration failed",
        "Unauthorized request detected",
        "Socket connection closed unexpectedly",
        "JSON parsing error occurred",
        "Timeout while waiting for server response",
        "Failed to write file to disk",
        "Invalid token provided",
        "Unhandled exception in ViewModel",
        "Crash occurred during initialization",
        "API returned 500 Internal Server Error",
        "Data integrity violation detected",
        "Failed to decode image resource",
        "Permission denied for requested operation",
        "OutOfMemoryError occurred",
        "IllegalStateException thrown",
        "Failed to bind service",
        "Coroutine was cancelled unexpectedly",
        "Deadlock detected in background thread",
        "SSL handshake failed",
        "Invalid response format",
        "Failed to load configuration",
        "Critical dependency missing"
    )
}