package com.zr.nebula.activity

import android.content.Intent
import android.graphics.Color
import android.os.Bundle
import androidx.activity.result.contract.ActivityResultContracts.CreateDocument
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.FileProvider
import androidx.core.view.isVisible
import com.zr.nebula.R
import com.zr.nebula.databinding.ActivityLogListBinding
import com.zr.nebula.extension.toCurrency
import com.zr.nebula.data.item.Log
import com.zr.nebula.helper.FileProviderUtil
import java.io.File
import java.io.FileWriter

internal class MainActivity : AppCompatActivity() {
    companion object {
        const val FILE_HEADER = "--- Logs Generated by Nebula Library ---\n--- https://github.com/zihadrizkyef/Nebula ---\n\n\n"
    }

    private lateinit var binding: ActivityLogListBinding
    private val viewModel = MainViewModel()

    private val saveFileLauncher = registerForActivityResult(CreateDocument("text/plain")) { uri ->
        uri?.let {
            contentResolver.openOutputStream(it).use { outputStream ->
                val text = viewModel.logs.value!!.joinToString("\n\n")
                outputStream?.write(FILE_HEADER.toByteArray())
                outputStream?.write(text.toByteArray())
            }
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityLogListBinding.inflate(layoutInflater)
        setContentView(binding.root)

        binding.refreshLayout.setColorSchemeColors(Color.parseColor("#111199"))
        binding.refreshLayout.isEnabled = false

        val list = listOf<Log>()
        val adapter = LogAdapter(list)
        binding.recyclerLog.adapter = adapter

        binding.buttonDelete.setOnClickListener {
            viewModel.deleteAll()
        }

        binding.buttonShare.setOnClickListener {
            viewModel.logs.value?.let { logs ->
                val text = logs.joinToString("\n\n")

                //writing log to file
                val path = File(filesDir, "nebula")
                val file = File(path, "nebula_log.txt")
                path.mkdirs()
                FileWriter(file).use { writer ->
                    writer.write(FILE_HEADER)
                    writer.write(text)
                }

                //sharing file
                val uri = FileProviderUtil.getUriForFile(this, file)
                val intent = Intent(Intent.ACTION_SEND).apply {
                    type = "text/plain"
                    putExtra(Intent.EXTRA_STREAM, uri)
                    addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION) // Grant read permission to the recipient app
                }
                startActivity(Intent.createChooser(intent, "Share File"))
            }
        }

        binding.buttonSave.setOnClickListener {
            viewModel.logs.value?.let {
                saveFileLauncher.launch("nebula_log.txt")
            }
        }

        viewModel.logs.observe(this) {
            binding.textCounter.text = getString(R.string.n_logs, it.size.toCurrency(false))
            binding.textEmpty.isVisible = it.isEmpty()
            adapter.logs = it
            adapter.notifyDataSetChanged()
        }

        viewModel.isLoading.observe(this) {
            binding.refreshLayout.isRefreshing = it
        }
    }
}