package com.zr.nebula.activity

import android.content.Intent
import android.graphics.Color
import android.Manifest
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.widget.Toast
import androidx.activity.enableEdgeToEdge
import androidx.activity.result.contract.ActivityResultContracts.CreateDocument
import androidx.activity.result.contract.ActivityResultContracts.RequestPermission
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.core.content.FileProvider
import androidx.lifecycle.lifecycleScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import androidx.core.view.ViewCompat
import androidx.core.view.WindowCompat
import androidx.core.view.WindowInsetsCompat
import androidx.core.view.isVisible
import androidx.core.view.updatePadding
import com.zr.nebula.R
import com.zr.nebula.data.item.Log
import com.zr.nebula.databinding.ActivityNebulaLogBinding
import com.zr.nebula.extension.dp
import com.zr.nebula.extension.toCurrency
import java.io.File
import java.io.FileWriter
import java.io.OutputStreamWriter
import java.io.Writer
import java.text.SimpleDateFormat
import java.util.Locale
import android.util.JsonWriter

internal class NebulaLogActivity : AppCompatActivity() {
    companion object {
        const val METADATA = "Logs Generated by Nebula Library - https://github.com/zihadrizkyef/Nebula"
    }

    private lateinit var binding: ActivityNebulaLogBinding
    private val viewModel = MainViewModel()

    private val requestPermissionLauncher = registerForActivityResult(
        RequestPermission()
    ) { _ -> }

    private val saveFileLauncher = registerForActivityResult(CreateDocument("application/json")) { uri ->
        uri?.let {
            binding.layoutLoading.isVisible = true
            lifecycleScope.launch(Dispatchers.IO) {
                var isSuccess = false
                try {
                    contentResolver.openOutputStream(it).use { outputStream ->
                        if (outputStream != null) {
                            OutputStreamWriter(outputStream).use { writer ->
                                writeLogsToJson(viewModel.logs.value ?: emptyList(), writer)
                            }
                        }
                    }
                    isSuccess = true
                } catch (e: Exception) {
                    e.printStackTrace()
                }
                withContext(Dispatchers.Main) {
                    binding.layoutLoading.isVisible = false
                    if (isSuccess) {
                        Toast.makeText(this@NebulaLogActivity, "Logs saved successfully", Toast.LENGTH_SHORT).show()
                    } else {
                        Toast.makeText(this@NebulaLogActivity, "Failed to save logs", Toast.LENGTH_SHORT).show()
                    }
                }
            }
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            if (ContextCompat.checkSelfPermission(
                    this,
                    Manifest.permission.POST_NOTIFICATIONS
                ) != PackageManager.PERMISSION_GRANTED
            ) {
                requestPermissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)
            }
        }

        enableEdgeToEdge()
        binding = ActivityNebulaLogBinding.inflate(layoutInflater)
        setContentView(binding.root)
        ViewCompat.setOnApplyWindowInsetsListener(window.decorView) { _, windowInsets ->
            val systemBarInsets = windowInsets.getInsets(WindowInsetsCompat.Type.systemBars())
            binding.toolbar.updatePadding(top = systemBarInsets.top + 8.dp(this))
            binding.recyclerLog.updatePadding(bottom = systemBarInsets.bottom)
            WindowInsetsCompat.CONSUMED
        }
        WindowCompat.getInsetsController(window, window.decorView).run {
            isAppearanceLightStatusBars = false
            isAppearanceLightNavigationBars = true
        }

        binding.refreshLayout.setColorSchemeColors(Color.parseColor("#111199"))
        binding.refreshLayout.isEnabled = false

        val list = listOf<Log>()
        val adapter = LogAdapter(list)
        binding.recyclerLog.adapter = adapter

        binding.buttonDelete.setOnClickListener {
            viewModel.deleteAll()
        }

        binding.buttonShare.setOnClickListener {
            viewModel.logs.value?.let { logs ->
                binding.layoutLoading.isVisible = true
                lifecycleScope.launch(Dispatchers.IO) {
                    var isSuccess = false
                    var exportedFile: File? = null
                    try {
                        val path = File(filesDir, "nebula")
                        val file = File(path, "nebula_log.json")
                        path.mkdirs()
                        FileWriter(file).use { writer ->
                            writeLogsToJson(logs, writer)
                        }
                        exportedFile = file
                        isSuccess = true
                    } catch (e: Exception) {
                        e.printStackTrace()
                    }

                    withContext(Dispatchers.Main) {
                        binding.layoutLoading.isVisible = false
                        if (isSuccess && exportedFile != null) {
                            Toast.makeText(this@NebulaLogActivity, "Logs exported successfully", Toast.LENGTH_SHORT).show()
                            val authority = "${applicationContext.packageName}.nebula.fileprovider"
                            val uri = FileProvider.getUriForFile(this@NebulaLogActivity, authority, exportedFile)
                            val intent = Intent(Intent.ACTION_SEND).apply {
                                type = "application/json"
                                putExtra(Intent.EXTRA_STREAM, uri)
                                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                            }
                            startActivity(Intent.createChooser(intent, "Share File"))
                        } else {
                            Toast.makeText(this@NebulaLogActivity, "Failed to export logs", Toast.LENGTH_SHORT).show()
                        }
                    }
                }
            }
        }

        binding.buttonSave.setOnClickListener {
            viewModel.logs.value?.let {
                saveFileLauncher.launch("nebula_log.json")
            }
        }

        viewModel.logs.observe(this) {
            binding.textCounter.text = getString(R.string.n_logs, it.size.toCurrency(false))
            binding.textEmpty.isVisible = it.isEmpty()
            adapter.logs = it
            adapter.notifyDataSetChanged()
        }

        viewModel.isLoading.observe(this) {
            binding.refreshLayout.isRefreshing = it
        }
    }

    private fun writeLogsToJson(logs: List<Log>, writer: Writer) {
        val jsonWriter = JsonWriter(writer)
        jsonWriter.setIndent("    ")
        jsonWriter.beginObject()
        jsonWriter.name("metadata").value(METADATA)
        jsonWriter.name("logs").beginArray()
        val sdf = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
        for (log in logs) {
            jsonWriter.beginObject()
            jsonWriter.name("id").value(log.id)
            jsonWriter.name("levelCode").value(log.levelCode)
            jsonWriter.name("message").value(log.message)
            jsonWriter.name("createdAt").value(sdf.format(log.createdAt))
            jsonWriter.endObject()
        }
        jsonWriter.endArray()
        jsonWriter.endObject()
        jsonWriter.flush()
    }
}